def optimize_design():
    ...


class Fan():
    def __init__(self):
        ...

    def estimate_efficiency(self):
        ...

    def generate_design(self):
        ...

    def establish_velocity_triangles(self):
        ...

    def calc_mixing_loss(self):
        ...

    def calc_BL_loss(self):
        ...

    def calc_endwall_loss(self):
        ...

    def calc_tip_leakage_loss(self):
        ...

    def calc_shock_loss(self):
        ...

    def calc_stall_margin(self):
        ...
